library(testthat)
source("R/balanceFactors.R")
source("R/confusion_matrix.R")
source("R/robustPE.R")
source("R/ROCtest.R")
source("R/modsearch.R")

test_file("inst/tests/test-caretobjects.R")
test_file("inst/tests/test-glmobjects.R")
test_file("inst/tests/test-modsearch.R")
#test_file("test-utilities")